### ISSUE TITLE
升级fc-plugin的runtime, 还有node版本

### ISSUE THREAD

**Issue by bingtsingw** [cellbang/malagu#199]
<img width="873" alt="image" src="https://github.com/cellbang/malagu/assets/10382462/ad93d528-bcef-49da-a230-22adf360765e">
`custom`的`runtime`会被锁定到 `debian9`版本, 后续不会再升级, 可以升级到`custom.debian10`

另外function和layer不同的runtime是不兼容的, 如果我想添加一个`node18`版本, 需要添加`malagu-node18-custom.yml` `malagu-node18-custom-debian10.yml`两个版本? 又或者`layer:name`和`compatibleRuntime`字段动态生成, 去获取`function.runtime`

**Comment by bingtsingw** [comment]
不知道这样是否可行
`malagu-node18.yml: `
```
malagu:
  cloud:
    layer:
      name: node-v18-18-2-linux-x64-${malagu.cloud.function.runtime}
      compatibleRuntime:
        - ${function.runtime}
      codeUri: https://nodejs.org/dist/v18.18.2/node-v18.18.2-linux-x64.tar.gz
    function:
      env:
        PATH: /opt/node-v18.18.2-linux-x64/bin:$PATH
      layers:
        - node-v18-18-2-linux-x64-${malagu.cloud.function.runtime}
```
